# Generated by Django 3.0.4 on 2020-03-23 12:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200323_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='profile_pic',
            field=models.ImageField(upload_to=account.models.user_directory_path),
        ),
    ]
