# Generated by Django 3.0.4 on 2020-03-23 13:09

import custom_admin.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to=custom_admin.models.user_directory_path)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('Ghana', 'Ghana'), ('South Africa', 'South Africa')], max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_telephone_no', models.CharField(blank=True, help_text='Start With 234', max_length=14, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
